// tests/integration/auth.test.js
//
// Full supertest flow against the real app + real DB, with src/services/resend
// mocked so no real emails are ever sent. Since resend is mocked, we
// recover the verification/reset codes the route actually generated by
// reading them straight out of the mock's captured call arguments —
// no need to peek at the database's auth_tokens table directly.

const request = require('supertest');

require('dotenv').config();
const resendService = require('../../src/services/resend');
resendService.sendVerificationEmail = vi.fn().mockResolvedValue(undefined);
resendService.sendPasswordResetCodeEmail = vi.fn().mockResolvedValue(undefined);

const app = require('../../src/app');
const { sendVerificationEmail, sendPasswordResetCodeEmail } = resendService;
const { prisma, uniqueEmail, createUser, cleanupBusinesses } = require('../helpers/factory');

function lastCodeSentTo(mockFn, email) {
    const call = [...mockFn.mock.calls].reverse().find(([to]) => to === email);
    if (!call) throw new Error(`No email captured for ${email}`);
    return call[1];
}

describe('POST /auth/register', () => {
    const businessesToClean = [];

    beforeEach(() => {
        sendVerificationEmail.mockClear();
        sendPasswordResetCodeEmail.mockClear();
    });

    afterAll(async () => {
        await cleanupBusinesses(...businessesToClean);
    });

    it('rejects when required fields are missing', async () => {
        const res = await request(app).post('/auth/register').send({ email: uniqueEmail() });
        expect(res.status).toBe(400);
        expect(res.body.error).toMatch(/required/i);
    });

    it('rejects passwords shorter than 8 characters', async () => {
        const res = await request(app).post('/auth/register').send({
            business_name: 'Test Biz',
            name: 'Test Owner',
            email: uniqueEmail(),
            password: 'short',
            facebook_contact: '9800000000',
        });
        expect(res.status).toBe(400);
        expect(res.body.error).toMatch(/8 characters/i);
    });

    it('creates a pending business/user and sends a verification email', async () => {
        const email = uniqueEmail();
        const res = await request(app).post('/auth/register').send({
            business_name: 'Test Biz',
            name: 'Test Owner',
            email,
            password: 'Password123!',
            facebook_contact: '9800000000',
        });

        expect(res.status).toBe(201);
        expect(res.body).toEqual({ email });
        expect(sendVerificationEmail).toHaveBeenCalledWith(email, expect.stringMatching(/^\d{6}$/));

        const user = await prisma.users.findUnique({ where: { email } });
        expect(user.status).toBe('pending');
        expect(user.role).toBe('admin');
        businessesToClean.push(user.business_id);
    });

    it('rejects duplicate registration for an already-active email', async () => {
        const { user, business } = await createUser({ status: 'active' });
        businessesToClean.push(business.id);

        const res = await request(app).post('/auth/register').send({
            business_name: 'Another Biz',
            name: 'Someone Else',
            email: user.email,
            password: 'Password123!',
            facebook_contact: '9811111111',
        });

        expect(res.status).toBe(409);
        expect(res.body.error).toMatch(/already in use/i);
    });

    it('allows re-registration to resume a signup that was left in a completed-password pending state', async () => {
        // Mirrors the one branch of the register route where an existing
        // 'pending' user with a password_hash already set is allowed to
        // re-register (overwriting name/password/business name) rather
        // than being blocked with 409.
        const { user, business } = await createUser({ status: 'pending', password: 'OldPassword1' });
        businessesToClean.push(business.id);

        const res = await request(app).post('/auth/register').send({
            business_name: 'Renamed Biz',
            name: 'New Name',
            email: user.email,
            password: 'NewPassword1',
            facebook_contact: '9822222222',
        });

        expect(res.status).toBe(201);
        const updatedBusiness = await prisma.businesses.findUnique({ where: { id: business.id } });
        expect(updatedBusiness.name).toBe('Renamed Biz');
    });
});

describe('POST /auth/verify-email', () => {
    let business;
    let user;
    let email;

    beforeEach(async () => {
        sendVerificationEmail.mockClear();
        email = uniqueEmail();
        const res = await request(app).post('/auth/register').send({
            business_name: 'Verify Biz',
            name: 'Verify Owner',
            email,
            password: 'Password123!',
            facebook_contact: '9800000000',
        });
        expect(res.status).toBe(201);
        user = await prisma.users.findUnique({ where: { email } });
        business = { id: user.business_id };
    });

    afterEach(async () => {
        await cleanupBusinesses(business);
    });

    it('rejects a wrong code', async () => {
        const res = await request(app).post('/auth/verify-email').send({ email, code: '000000' });
        expect(res.status).toBe(400);
        expect(res.body.error).toMatch(/invalid or expired/i);
    });

    it('rejects an expired code', async () => {
        const code = lastCodeSentTo(sendVerificationEmail, email);
        await prisma.auth_tokens.updateMany({
            where: { user_id: user.id, type: 'email_verify' },
            data: { expires_at: new Date(Date.now() - 1000) },
        });
        const res = await request(app).post('/auth/verify-email').send({ email, code });
        expect(res.status).toBe(400);
    });

    it('accepts the correct code and returns a session token', async () => {
        const code = lastCodeSentTo(sendVerificationEmail, email);
        const res = await request(app).post('/auth/verify-email').send({ email, code });

        expect(res.status).toBe(200);
        expect(res.body.token).toEqual(expect.any(String));
        expect(res.body.user.email).toBe(email);
        expect(res.body.user.status).toBe('pending_approval');
        // Never leak the password hash in an auth response.
        expect(res.body.user.password_hash).toBeUndefined();
    });

    it('rejects reusing an already-consumed code', async () => {
        const code = lastCodeSentTo(sendVerificationEmail, email);
        const first = await request(app).post('/auth/verify-email').send({ email, code });
        expect(first.status).toBe(200);

        const second = await request(app).post('/auth/verify-email').send({ email, code });
        expect(second.status).toBe(400);
    });
});

describe('POST /auth/login', () => {
    let activeBiz, activeUser, activePassword;
    let pendingBiz, pendingUser;
    let rejectedBiz, rejectedUser;

    beforeAll(async () => {
        ({ business: activeBiz, user: activeUser, password: activePassword } = await createUser({
            status: 'active',
            password: 'CorrectPassword1',
        }));
        ({ business: pendingBiz, user: pendingUser } = await createUser({ status: 'pending' }));
        ({ business: rejectedBiz, user: rejectedUser } = await createUser({ status: 'rejected' }));
    });

    afterAll(async () => {
        await cleanupBusinesses(activeBiz, pendingBiz, rejectedBiz);
    });

    it('returns 400 when email or password is missing', async () => {
        const res = await request(app).post('/auth/login').send({});
        expect(res.status).toBe(400);
    });

    it('logs in successfully with correct credentials', async () => {
        const res = await request(app)
            .post('/auth/login')
            .send({ email: activeUser.email, password: activePassword });
        expect(res.status).toBe(200);
        expect(res.body.token).toEqual(expect.any(String));
        expect(res.body.user.email).toBe(activeUser.email);
    });

    it('rejects wrong password with 401 "Invalid email or password"', async () => {
        const res = await request(app)
            .post('/auth/login')
            .send({ email: activeUser.email, password: 'WrongPassword1' });
        expect(res.status).toBe(401);
        expect(res.body.error).toBe('Invalid email or password');
    });

    it('rejects a nonexistent email with the exact same message (no user-enumeration leak)', async () => {
        const res = await request(app)
            .post('/auth/login')
            .send({ email: uniqueEmail('doesnotexist'), password: 'WhateverPassword1' });
        expect(res.status).toBe(401);
        expect(res.body.error).toBe('Invalid email or password');
    });

    it('blocks login for an unverified (pending) account with EMAIL_NOT_VERIFIED', async () => {
        const res = await request(app)
            .post('/auth/login')
            .send({ email: pendingUser.email, password: 'Password123!' });
        // pendingUser has no known plaintext password matching a fixed
        // value from the factory default, so this must fail before ever
        // reaching the status check if the factory default password
        // ('Password123!') isn't what was hashed. The factory always
        // hashes the returned `password`, and default password is
        // 'Password123!', so this matches.
        expect(res.status).toBe(403);
        expect(res.body.code).toBe('EMAIL_NOT_VERIFIED');
    });

    it('blocks login for a rejected application with APPLICATION_REJECTED', async () => {
        const res = await request(app)
            .post('/auth/login')
            .send({ email: rejectedUser.email, password: 'Password123!' });
        expect(res.status).toBe(403);
        expect(res.body.code).toBe('APPLICATION_REJECTED');
    });
});

describe('GET /auth/me', () => {
    let business, user, token;

    beforeAll(async () => {
        ({ business, user } = await createUser({ status: 'active' }));
        const loginRes = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'Password123!' });
        token = loginRes.body.token;
    });

    afterAll(async () => {
        await cleanupBusinesses(business);
    });

    it('returns the current user with a valid token', async () => {
        const res = await request(app).get('/auth/me').set('Authorization', `Bearer ${token}`);
        expect(res.status).toBe(200);
        expect(res.body.email).toBe(user.email);
        expect(res.body.password_hash).toBeUndefined();
    });

    it('rejects when no Authorization header is present', async () => {
        const res = await request(app).get('/auth/me');
        expect(res.status).toBe(401);
    });

    it('rejects an invalid/garbage token', async () => {
        const res = await request(app).get('/auth/me').set('Authorization', 'Bearer not-a-real-token');
        expect(res.status).toBe(401);
    });
});

describe('Forgot-password / reset-password flow', () => {
    let business, user;

    beforeEach(async () => {
        sendPasswordResetCodeEmail.mockClear();
        ({ business, user } = await createUser({ status: 'active', password: 'OriginalPassword1' }));
    });

    afterEach(async () => {
        await cleanupBusinesses(business);
    });

    it('always returns a generic message, even for an unknown email, and does not send an email for it', async () => {
        const res = await request(app)
            .post('/auth/forgot-password')
            .send({ email: uniqueEmail('unknown') });
        expect(res.status).toBe(200);
        expect(res.body.message).toMatch(/if that email has an account/i);
        expect(sendPasswordResetCodeEmail).not.toHaveBeenCalled();
    });

    it('sends a reset code for a known active account', async () => {
        const res = await request(app).post('/auth/forgot-password').send({ email: user.email });
        expect(res.status).toBe(200);
        expect(sendPasswordResetCodeEmail).toHaveBeenCalledWith(user.email, expect.stringMatching(/^\d{6}$/));
    });

    it('rejects reset with a wrong code', async () => {
        await request(app).post('/auth/forgot-password').send({ email: user.email });
        const res = await request(app)
            .post('/auth/reset-password')
            .send({ email: user.email, code: '000000', password: 'NewPassword1' });
        expect(res.status).toBe(400);
    });

    it('resets the password with the correct code and allows login with the new password', async () => {
        await request(app).post('/auth/forgot-password').send({ email: user.email });
        const code = lastCodeSentTo(sendPasswordResetCodeEmail, user.email);

        const resetRes = await request(app)
            .post('/auth/reset-password')
            .send({ email: user.email, code, password: 'BrandNewPassword1' });
        expect(resetRes.status).toBe(200);

        const loginOld = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'OriginalPassword1' });
        expect(loginOld.status).toBe(401);

        const loginNew = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'BrandNewPassword1' });
        expect(loginNew.status).toBe(200);
    });

    it('rejects a new password under 8 characters', async () => {
        await request(app).post('/auth/forgot-password').send({ email: user.email });
        const code = lastCodeSentTo(sendPasswordResetCodeEmail, user.email);
        const res = await request(app)
            .post('/auth/reset-password')
            .send({ email: user.email, code, password: 'short' });
        expect(res.status).toBe(400);
    });
});

describe('POST /auth/change-password', () => {
    let business, user, token;

    beforeAll(async () => {
        ({ business, user } = await createUser({ status: 'active', password: 'CurrentPassword1' }));
        const loginRes = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'CurrentPassword1' });
        token = loginRes.body.token;
    });

    afterAll(async () => {
        await cleanupBusinesses(business);
    });

    it('rejects when currentPassword is wrong', async () => {
        const res = await request(app)
            .post('/auth/change-password')
            .set('Authorization', `Bearer ${token}`)
            .send({ currentPassword: 'WrongOne1', newPassword: 'SomethingNew1' });
        expect(res.status).toBe(401);
    });

    it('rejects a new password under 8 characters', async () => {
        const res = await request(app)
            .post('/auth/change-password')
            .set('Authorization', `Bearer ${token}`)
            .send({ currentPassword: 'CurrentPassword1', newPassword: 'short' });
        expect(res.status).toBe(400);
    });

    it('changes the password and allows login with the new one', async () => {
        const res = await request(app)
            .post('/auth/change-password')
            .set('Authorization', `Bearer ${token}`)
            .send({ currentPassword: 'CurrentPassword1', newPassword: 'UpdatedPassword1' });
        expect(res.status).toBe(200);

        const loginRes = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'UpdatedPassword1' });
        expect(loginRes.status).toBe(200);
    });
});

describe('PATCH /auth/profile', () => {
    let business, user, token;

    beforeAll(async () => {
        ({ business, user } = await createUser({ status: 'active' }));
        const loginRes = await request(app)
            .post('/auth/login')
            .send({ email: user.email, password: 'Password123!' });
        token = loginRes.body.token;
    });

    afterAll(async () => {
        await cleanupBusinesses(business);
    });

    it('rejects an empty name', async () => {
        const res = await request(app)
            .patch('/auth/profile')
            .set('Authorization', `Bearer ${token}`)
            .send({ name: '   ' });
        expect(res.status).toBe(400);
    });

    it('updates the display name', async () => {
        const res = await request(app)
            .patch('/auth/profile')
            .set('Authorization', `Bearer ${token}`)
            .send({ name: 'Updated Name' });
        expect(res.status).toBe(200);
        expect(res.body.name).toBe('Updated Name');
    });

    it('rejects when not authenticated', async () => {
        const res = await request(app).patch('/auth/profile').send({ name: 'No Auth' });
        expect(res.status).toBe(401);
    });
});
